implements --init-bare to initialize a new bare git repository
Can be used in conjuction with --seat DIR to specify desired dir.

diff --git a/.local/bin/xadf b/.local/bin/xadf
--- a/.local/bin/xadf
+++ b/.local/bin/xadf
@@ -44,6 +44,7 @@ vanilla_xadf=0
 build_recipe=0
 build_xadfrc=0
 touch_bashrc=0
+init_bare=0
 install_mode=0
 install_seat="$HOME/xadf"
 install_branch="trunk"
@@ -97,6 +98,18 @@ then
 else
 	printf "[xadf]: xadfrc is appended to ~/.bashrc...DONE\n"
 fi
+}
+
+xadf_init_bare(){
+	printf "[xadf]: Initialize a bare directory at '%s'..." "$install_seat"
+	git init --bare "$install_seat"
+	if test $? -gt 0
+	then
+		printf "FAIL\n"
+		exit 15
+	else
+		printf "OK\n"
+	fi
 }
 
 xadf_install(){
@@ -302,6 +315,9 @@ Normal usage options:
                             \$xadfmods/template-xadfrc
   --touch-bashrc/-t         Modify .bashrc to include a line to source xadfrc
                             if it is not already present.
+  --init-bare               Initialize a bare git repository at \$HOME. Can be
+                            used in conjuction with --seat option to specify
+                            custom location.                Default: \$HOME/xadf
   --custom-seat/-c DIR      Sets xadf git directory to DIR. Unlike --seat,
                             the next options will be assumed to be git
                             commands. Useful to use an alternative git
@@ -397,6 +413,9 @@ while :; do
 			export touch_bashrc=1
 			shift
 			;;
+		--init-bare )
+			export init_bare=1
+			shift
 		--xadf-repo ) # changes upstream url
 			export vanilla_xadf=1
 			shift
@@ -463,6 +482,11 @@ fi
 if test $touch_bashrc -eq 1
 then
 	xadf_touch_bashrc
+fi
+
+if test $init_bare -eq 1
+then
+	xadf_init_bare
 fi
 
 if test $vanilla_xadf -eq 1 || test $set_origin_url -eq 1
