first draft of xadf and its ecosystem is completed

diff --git a/.local/bin/xadf b/.local/bin/xadf
--- a/.local/bin/xadf
+++ b/.local/bin/xadf
@@ -46,22 +46,143 @@ build_xadfrc=0
 install_mode=0
 install_seat="$HOME/xadf"
 install_branch="trunk"
+xadf_https_repo="https://github.com/heno72/xadf.git"
 
 xadf_build_recipe(){
 # builds recipe
-echo "builds recipe"
+printf "[xadf]: Generate recipe..."
+cat ~/.local/xadf/default-recipe.txt > ~/.config/xadf/recipe.txt
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 4
+else
+	printf "DONE\n"
+fi
 }
 
 xadf_build_xadfrc(){
 # builds xadfrc
-echo "builds xadfrc"
+printf "[xadf]: Generate xadfrc..."
+. ~/.local/xadf/template-xadfrc | sed "s#$HOME#\$HOME#" > ~/.config/xadf/xadfrc
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 5
+else
+	printf "DONE\n"
+fi
 }
 
 xadf_install(){
 # installs xadf
-echo "installs xadf"
-echo "seat is: $install_seat"
-echo "branch is: $install_branch"
+printf "[xadf]: installing xadf\n"
+printf "[xadf]: seat is '%s'\n" "$install_seat"
+printf "[xadf]: branch is '%s'\n" "$install_branch"
+
+# 1. Replicate from xadf git repository with separate git configuration.
+#    It will also specify a temporary location $HOME/.xadf-tmp to store
+#    all contents of the repo. If --seat is set, replicate git directory
+#    to the specified location. Otherwise, replicate git directory to
+#    $HOME/xadf
+printf "[xadf]: Clone from repo '%s'..." "$xadf_https_repo"
+git clone --separate-git-dir="$install_seat" "$xadf_https_repo" ~/.xadf-tmp
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 6
+else
+	printf "DONE\n"
+fi
+
+# 2. Switch working directory to temporary working directory
+printf "[xadf]: Switch working directory to '~/.xadf-tmp'..."
+pushd ~/.xadf-tmp
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 7
+else
+	printf "DONE\n"
+fi
+
+# 3. If --branch is set, checks out to branch NAME
+printf "[xadf]: Checks out to branch '%s'..." "$install_branch"
+git --git-dir="$install_seat" --work-tree="$HOME" checkout -b "$install_branch"
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 8
+else
+	printf "DONE\n"
+fi
+
+# 4. rsync all contents of $HOME/.xadf-tmp/ except '.git' to $HOME
+printf "[xadf]: Syncinc repo to '%s'..." "$HOME"
+rsync --recursive --verbose --exclude '.git' "~/.xadf-tmp/" "$HOME/"
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 9
+else
+	printf "DONE\n"
+fi
+
+# 5. Removes $HOME/.xadf-tmp/
+printf "[xadf]: Returns to '%s'..." "$HOME"
+popd
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 10
+else
+	printf "DONE\n"
+fi
+
+printf "[xadf]: Deletes temporary working directory '~/.xadf-tmp'..."
+rm -rf "~/.xadf-tmp"
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 11
+else
+	printf "DONE\n"
+fi
+
+# 6. Make untracked files not shown: xadf config status.showUntrackedFiles no
+printf "[xadf]: Makes untracked file not shown..."
+git --git-dir="$install_seat" --work-tree="$HOME" config status.showUntrackedFiles no
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 12
+else
+	printf "DONE\n"
+fi
+
+# 7. Check if .bashrc exists. If exists, go to 9, else go to 8
+# 8. Copy from /etc/skel/.bashrc to ~/.bashrc, and continue to 10
+test ! -f "$HOME/.bashrc" && cp /etc/skel/.bashrc ~/.bashrc
+
+# 9. If .bashrc does not contain . ~/.config/xadf/xadfrc, appends that
+#    line to the end of ~/.bashrc. Note that it should at first strip all
+#    comments off by piping to sed (does not modify .bashrc) and then
+#    performs grep search
+printf "[xadf]: Ensures xadfrc is sourced in ~.bashrc..."
+sed 's/#.*$//' ~/.bashrc|grep "^. ~/\.config/xadf/xadfrc$"
+test $? -gt 0 && printf ". ~/.config/xadf/xadfrc\n" >> ~/.bashrc
+if test $? -gt 0
+then
+	printf "FAIL\n"
+	exit 12
+else
+	printf "DONE\n"
+fi
+
+# 10. Builds xadfrc from $xadfmods/template-xadfrc with xadf -x (honors --seat option)
+test ! -f ~/.config/xadfrc && "$0" -x
+# 11. If no recipe.txt is present, builds recipe.txt with xadf -r
+test ! -f ~/.config/recipe.txt && "$0" -r
 }
 
 xadf_version(){
@@ -144,7 +265,7 @@ while :; do
 			# specify which file or directory do we want to see (just like ls in some
 			# ways).
 			shift
-			xadf ls-tree --full-tree -r --name-only HEAD "$@"
+			"$0" ls-tree --full-tree -r --name-only HEAD "$@"
 			exit 0
 			;;
 		-h | --help ) # show help text, then exit
@@ -166,7 +287,6 @@ while :; do
 			if test -z "$2"
 			then
 				printf >&2 "Error: No directory is set!\nUsage: xadf -h\n\n"
-
 				exit 1
 			else
 				export install_seat="$2"
@@ -201,13 +321,14 @@ while :; do
 			printf >&2 "Error: Invalid flag '%s'\nUsage: xadf -h\n\n" "$1"
 			xadf_show_help
 			shift
-			exit 1
+			exit 3
 			;;
 		"" ) # No options
 			break
 			;;
 		* ) # Practically a git alias with separate git dir
-			git --git-dir="$xadfdir" --work-tree="$HOME" "$@"
+			# If $xadfdir is not set, then fail
+			test -n "$xadfdir" && git --git-dir="$xadfdir" --work-tree="$HOME" "$@"
 			break
 			;;
 	esac
@@ -233,5 +354,10 @@ fi
 
 if test $is_heno -eq 1
 then
-	xadf remote set-url origin git@github.com:heno72/xadf.git
+	if test -n "$xadfdir"
+	then # xadfdir is set, xadf will call itself as an alias
+		"$0" remote set-url origin git@github.com:heno72/xadf.git
+	else # is set in installation, will call the raw commands
+		git --git-dir="$install_seat" --work-tree="$HOME" remote set-url origin git@github.com:heno72/xadf.git
+	fi
 fi
